
const TITLE_TEXT_FONT_SIZE = 24.0;
const SUBTITLE_FONT_SIZE = 14.0;
const BUTTON_FONT_SIZE = 16.0;
const BODY1_TEXT_FONT_SIZE = 18.0;
const APPBAR_HEADER = 18.0;
const CAPTION_SMALLER_TEXT_FONT_SIZE = 12.0;
const CAPTION_BIG_TEXT2_FONT_SIZE = 22.0;

const BODY2_TEXT_FONT_SIZE = 19.0;
const CAPTION_BIGGER_TEXT_FONT_SIZE = 23.0;
const CAPTION_BIG_TEXT_FONT_SIZE = 21.0;
const CAPTION_TEXT_FONT_SIZE = 15.0;
const BODY3_TEXT_FONT_SIZE = 15.0;
const BODY4_TEXT_FONT_SIZE = 16.0;
const CAPTION_SMALLEST_TEXT_FONT_SIZE = 10.0;
const FORGET_PASSWORD_TEXT_FONT_SIZE = 14.0;

const CATEGORY_INITIAL_TEXT_FONT_SIZE = 20.0;

const BOTTOM_PADDING = 90.0;

const COMMON_DIVIDER_THICKNESS = 0.7;

const COMMON_BORDER_RADIUS = 6.0;

const LARGER_DIVIDER_THICKNESS = 8.0;
const PRODUCT_NAME_FONT_SIZE = 16.0;
const PRODUCT_PRICE_FONT_SIZE = 15.0;
const FILTER_ITEM_FONT_SIZE = 17.0;
const FILTER_SELECTED_ITEM_FONT_SIZE = 16.0;
const LIST_ITEM_FONT_SIZE = 16.0;
const PRICE_RANGE_FONT_SIZE = 19.0;
const TEXT_FIELD_FONT_SIZE = 16.0;
const USERNAME_FONT_SIZE = 21.0;
const REVIEWS_FONT_SIZE = 21.0;
const TEXT_FIELD_FONT_SIZE2 = 12.0;
const TEXT_FIELD_FONT_SIZE3 = 24.0;
const TEXT_FIELD_FONT_SIZE4 = 36.0;
const TEXT_FIELD_FONT_SIZE5 = 32.0;
const TEXT_FIELD_FONT_SIZE6 = 40.0;
const TEXT_FIELD_FONT_SIZE7 = 52.0;


//Padding

const HORIZONTAL_PADDING = 16.0;
const VERTICAL_PADDING = 8.0;
